services:
  live-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: live-adapter
    ports:
      - "8080:8080"
    volumes:
      - live-adapter-cds:/data
    networks:
      - shared-infra-network

networks:
  shared-infra-network:
    external: true

volumes:
  live-adapter-cds:
